# Generated by Django 4.1.1 on 2022-09-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
