# Generated by Django 4.1.1 on 2022-09-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='director',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
