# Generated by Django 4.1.1 on 2022-09-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
