# Generated by Django 4.1.1 on 2022-10-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_post_featured_post_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured',
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.CharField(default='Unfeatured', max_length=255),
        ),
    ]
