# Generated by Django 4.1.1 on 2022-10-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_post_featured_post_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='post',
            name='heroes',
            field=models.ManyToManyField(to='blog.featured'),
        ),
    ]
