# Generated by Django 4.1.3 on 2022-11-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_profile_bio_post_heroes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.SlugField(default='Unfeatured', max_length=255),
        ),
    ]
