# Generated by Django 4.1.3 on 2022-11-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='heroes',
        ),
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.CharField(max_length=255),
        ),
    ]
