# Generated by Django 4.1.3 on 2022-11-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_post_hero_post_heroes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='heroes',
        ),
        migrations.AddField(
            model_name='post',
            name='heroes',
            field=models.CharField(default='Unfeatured', max_length=255),
        ),
    ]
