# Generated by Django 4.1.3 on 2022-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_post_heroes_post_heroes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='heroes',
            field=models.CharField(blank=True, default='No additional heroes', max_length=255),
        ),
    ]
