# Generated by Django 4.1.3 on 2022-11-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_post_heroes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='heroes',
        ),
        migrations.AddField(
            model_name='post',
            name='heroes',
            field=models.ManyToManyField(to='blog.featured'),
        ),
    ]
