# Generated by Django 4.1.3 on 2022-11-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_remove_post_heroes_post_heroes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='heroes',
            field=models.ManyToManyField(blank=True, to='blog.featured'),
        ),
    ]
